[project]
name = "email_service"
version = "0.1.0"
description = "Email notification service for shipment updates"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
] 